### PR TITLE
Providing error message to python in exception

### LINKED ISSUE #225: Could BridgeRuntimeError contain more specific information about the failure?
When calls into the bridge fail, the exception 

```
nimbusml.internal.utils.entrypoints.BridgeRuntimeError: Returned 
code is -1. Check the log for error messages. 
```

is thrown. The specific exception the bridge encounters (like : *** System.InvalidOperationException: 'Sequence contains no matching element'...) appears only in the stdout

For our scenario, we don't keep a record of the stdout. We do have a try/catch around nimbus calls, and we write any exception nimbus throws to our logs. Because of this practice, our logs only contain `BridgeRuntimeError: Returned code is -1` and not more specific debug info

If it would be possible to add more specific info to the BridgeRuntimeError, it would definitely be appreciated in our scenario

### PR DESCRIPTION
**Pull request by ganik**
fixes #225

### CODE REVIEW

File: src/NativeBridge/dllmain.cpp [hunk 1]
```diff
@@ -114,11 +114,11 @@ bp::dict pxCall(bp::dict& params)
         else
             retCode = exec(&env, s_graph.c_str(), 0, NULL);
 
+        if (retCode == -1)
+            throw std::runtime_error(env.GetErrorMessage());
```
Comment (pieths) [inline src/NativeBridge/dllmain.cpp]: When this is -1 then the `GetData()` call will be skipped. Is this okay since it looks like the `PythonObject` instances which are owned by NativeBridge get deleted only if `GetData()` is called?

Comment (ganik) [reply src/NativeBridge/dllmain.cpp]: Great point! I ll put it back

---
In reply to: [326818751](https://github.com/microsoft/NimbusML/pull/273#discussion_r326818751) [](ancestors = 326818751)
